version: '3.8'

services:
  api:
    build:
      context: ./go/api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=0845635040
      - DB_NAME=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ecom-network

  worker:
    build:
      context: ./go/worker
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=0845635040
      - DB_NAME=postgres
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - ecom-network

  ui:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - ecom-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0845635040
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

