version: '3.8'

services:
  api:
    build:
      context: ./go/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - quote-my-move

  worker:
    build:
      context: ./go/worker
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - quote-my-move

  ui:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - quote-my-move

networks:
  quote-my-move:
    driver: bridge

